// dbNewFileDuplicateDlg.cpp : implementation file

#include "StdAfx.h"
#include "dbNewFileDuplicateDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

/////////////////////////////////////////////////////////////////////////////
// CdbNewFileDuplicateDlg dialog


CdbNewFileDuplicateDlg::CdbNewFileDuplicateDlg(CWnd* pParent /*=NULL*/)
	: CDialog(CdbNewFileDuplicateDlg::IDD, pParent)
{
	m_option = -1;
	m_pfilein= nullptr;
	m_csExt.Empty();
}


void CdbNewFileDuplicateDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	DDX_Radio(pDX, IDC_RADIO1, m_option);
}


BEGIN_MESSAGE_MAP(CdbNewFileDuplicateDlg, CDialog)
	ON_BN_CLICKED(IDC_RADIO3, OnRadio3)
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CdbNewFileDuplicateDlg message handlers

BOOL CdbNewFileDuplicateDlg::OnInitDialog() 
{
	CDialog::OnInitDialog();
	
	((CButton*) GetDlgItem(IDC_RADIO3))->SetCheck(TRUE);

	// check if file requested is already there
	CString csnew = m_pfilein;
	CFileStatus status;
	BOOL bExist = CFile::GetStatus(csnew, status);

	// decompose name
	int icount = csnew.ReverseFind('\\')+1;
	m_csPath = csnew.Left(icount);
	m_csName = csnew.Right(csnew.GetLength()-icount);
	GetDlgItem(IDC_STATIC1)->SetWindowText(m_csName);
	GetDlgItem(IDC_STATIC14)->SetWindowText(m_csPath);

	// if it is already there, find the root of the name (clip off any trailing numbers)
	// and iterate numbers until root+number is not found on disk
	if (bExist)
	{
		CString csRoot;	// root name of the file series
		
		// extract name without extension
		csnew = m_csName;
		int i = csnew.ReverseFind('.');
		ASSERT(i>0);
		if (i > 0)
		{
			m_csExt = csnew.Right(csnew.GetLength() - i);
			csRoot = csnew.Left(i);		
		}
		else
			csRoot = csnew;

		// get root name without numbers
		int j = csRoot.FindOneOf(_T("0123456789"));	// find the first numerical character
		// no numerical character is found, assume it is the first and add "1"
		if (j < 0)
			csnew = csRoot +_T("1");

		// numerical character found - iterate until a file name is found that is not used
		else
		{
			// assume here that all other characters are numerical
			// this should be OK if the filename was generated by the framework
			// increment the nb
			CString csnb;	// number associated with name
			csnb = csRoot.Right(csRoot.GetLength() - j);
			int nb = _ttoi(csnb);
			csRoot = csRoot.Left(j);
			
			BOOL bExist = TRUE;
			int jiterations = 50;		// limit nb of iterations to 50
			while (bExist && (jiterations > 0))
			{
				nb++;
				csnb.Format(_T("%i"),nb);
				CString csdummy = m_csPath + csRoot + csnb;
				csdummy += m_csExt;
				bExist = CFile::GetStatus(csdummy, status);
				jiterations--;			
			}
			csnew = csRoot + csnb;
		}
	}

	// tentative name defined - display it and exit
	GetDlgItem(IDC_EDIT1)->SetWindowText(csnew);
	return TRUE;  // return TRUE unless you set the focus to a control
	              // EXCEPTION: OCX Property Pages should return FALSE
}

void CdbNewFileDuplicateDlg::OnOK() 
{
	UpdateData(TRUE);
	GetDlgItem(IDC_EDIT1)->GetWindowText(m_csName);
	m_fileout = m_csPath + m_csName;
	if (!m_csExt.IsEmpty())
	{
		m_fileout += m_csExt;
	}
	CDialog::OnOK();
}

void CdbNewFileDuplicateDlg::OnRadio3() 
{
	GetDlgItem(IDC_EDIT1)->EnableWindow(((CButton*) GetDlgItem(IDC_RADIO3))->GetCheck());
}
